wallpaper {
    monitor = eDP-1
    path = /home/haithem/Pictures/backgrounds/nice-blue-background.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/haithem/Pictures/backgrounds/nice-blue-background.png
    fit_mode = cover
}

splash = false
ipc = true
